// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tloxqwzzzuzmukanovpb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRsb3hxd3p6enV6bXVrYW5vdnBiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMDIzMjAsImV4cCI6MjA2NTU3ODMyMH0.fE_p4VtW2H8lNlL4YNiZcJRXAnBK0wVhLE0bYMgitk4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);